IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'import' AND TABLE_NAME='People' AND COLUMN_NAME='_CreateDate')
AND (OBJECT_ID('DFLT_import_People_CreateDate') IS NOT NULL)
ALTER TABLE import.People DROP CONSTRAINT DFLT_import_People_CreateDate

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'import' AND TABLE_NAME='People')
DROP TABLE [import].[People]
GO

CREATE TABLE import.People
(
	PersonId INT NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	Email VARCHAR(200) NOT NULL,
	_Id INT IDENTITY NOT NULL PRIMARY KEY,
	_SourceFileName VARCHAR(200) NULL,
	_CreateDate datetime2 NOT NULL 
        CONSTRAINT DFLT_import_People_CreateDate DEFAULT (GETDATE())
)