--find any columns that have underscores in their name 
--(can use this to find columns automatically generated by entity framework code first 
--to support possibly unintended foreign key relationships.)
--by default like _ means any single character 
--but we want to literally search for the _ character
--thus use of ! and ESCAPE '!'
select * from INFORMATION_SCHEMA.COLUMNS where COLUMN_NAME like '%!_%' ESCAPE '!'